; platformio.ini  -  nodo del mini-cluster (Federer)
; Coloca esp32_nodo_ota.cpp como  src/main.cpp
; y el datos_nodo_k.h de cada nodo como  include/datos_nodo.h

[env:esp32dev]                 ; PRIMERA grabacion: por USB
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0

[env:esp32ota]                 ; SIGUIENTES grabaciones: por red (OTA)
extends = env:esp32dev
upload_protocol = espota
upload_flags =
    --auth=federer            ; debe coincidir con OTA_PASS del firmware
; el destino se pasa por linea de comando:  --upload-port <IP_DEL_NODO>
; (Federer lo hace automaticamente con la IP del registro)
